package com.simma.simmaapp.model.myOrdersModel

data class Merchant(
    val __v: Double,
    val _id: String,
    val cartUrl: String,
    val categorys: List<String>,
    val commission: CommissionX,
    val country: String,
    val coverImage: CoverImage,
    val coverIsActive: Boolean,
    val createdAt: String,
    val currencyId: String,
    val deals: List<Deal>,
    val demoMode: Boolean,
    val discounts: List<Discount>,
    val extraDeliveryPerItem: Double,
    val extractionCode: String,
    val id: String,
    val image: Image,
    val isCommissionElligible: Boolean,
    val isWoocommerce: Boolean,
    val maximumDaysToDeliver: Double,
    val minimumDaysToDeliver: Double,
    val name: Name,
    val onLoadCompleteCode: String,
    val paymentMethods: List<PaymentMethod>,
    val rank: Double,
    val scraperCodes: ScraperCodes,
    val status: String,
    val storeAbbreviation: String,
    val translation: Boolean,
    val updatedAt: String,
    val url: String,
    val cartCode : String
)